[package]
name = "notify_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.5"
notify = "5.1.0"
tokio = { version = "1.25.0", features = ["full"] }
